defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

title: jahndev
repository: renejahn/renejahn.github.io
domain: renejahn.github.io/
url: https://renejahn.github.io/
baseUrl: /

exclude:
  - _posts
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag