defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

domain: renejahn.github.io/
url: https://renejahn.github.io/
baseUrl: /

exclude:
  - _posts
  - node_modules

postcss:
  cache: false

plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-seo-tag
